apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Values.cronjob.name }}
spec:
  schedule: {{ $.Values.cronjob.schedule | quote}}
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
            - name: {{ include "app.fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ include "app.fullname" . }}
                - secretRef:
                    name: {{ include "app.fullname" . }}
              env:
              {{- toYaml .Values.env | nindent 16 }}
              volumeMounts:
              {{- toYaml .Values.volumeMounts | nindent 16 }}
          volumes:
            {{- toYaml .Values.volumes | nindent 16 }}
          restartPolicy: Never
