# batch reconcile jobs
# for tester docker.io/library/hello-world 

cronjob:
  name: simple-cronjob
  command: ./app/batch/simple-cronjob
  # Schedule at 04.00 AM everyday
  schedule: "0 21 * * *"
  # failedJobsHistoryLimit: 1
  # successfulJobsHistoryLimit: 3
  # concurrencyPolicy: Allow
  # restartPolicy: OnFailure

fullnameOverride: simple-cronjob
replicaCount: 1

image:
  repository: asia.gcr.io/poc-innovation-iot/simple-cronjob
  pullPolicy: Always
  tag: v1.0

service:
  type: ClusterIP
  port: 80

env:
  - name: API_CONFIG_PATH
    value: /config
  - name: API_CONFIG_NAME
    value: config

volumes:
  - name: simple-cronjob-gcs-sa
    secret:
      secretName: simple-cronjob
  - name: simple-cronjob-config
    configMap:
      name: simple-cronjob

volumeMounts:
  - name: simple-cronjob-config
    mountPath: /config
    readOnly: true
  - name: simple-cronjob-gcs-sa
    mountPath: /gcs-secret
    readOnly: true

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources:
  {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  
secrets:
  all:


